# Generated by Django 5.2 on 2025-04-29 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название удобства')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name="Класс иконки (например, 'icon-wifi')")),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отеля')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 звезд(ы)'), (2, '2 звезд(ы)'), (3, '3 звезд(ы)'), (4, '4 звезд(ы)'), (5, '5 звезд(ы)')], verbose_name='Рейтинг (звезды)')),
                ('main_image', models.ImageField(upload_to='hotel_images/', verbose_name='Главное изображение')),
                ('amenities', models.ManyToManyField(blank=True, to='hotels.amenity', verbose_name='Удобства')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа номера')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание номера')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена за ночь (KGS)')),
                ('capacity', models.PositiveSmallIntegerField(default=2, verbose_name='Вместимость (чел.)')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
                'ordering': ['hotel', 'base_price'],
            },
        ),
    ]
