# Generated by Django 5.2 on 2025-05-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_amenity_name_en_amenity_name_ky_amenity_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_special_offer',
            field=models.BooleanField(default=False, help_text='Отметьте, если для этого отеля есть действующая акция', verbose_name='Специальное предложение?'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='special_offer_description',
            field=models.CharField(blank=True, help_text="Например: '-15% на выходные', 'Завтрак в подарок'", max_length=255, null=True, verbose_name='Описание спецпредложения'),
        ),
    ]
